// app/layout.tsx - CORRECTED FINAL VERSION

import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs';
// 1. All necessary imports must be at the very top
import { Geist, Geist_Mono } from "next/font/google"; 
import "./globals.css";

// Assuming your Navbar is here:
import Navbar from '../components/Navbar'; 


// 2. The font variable declarations must be at the top level (global scope)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({ // <-- This is where 'geistMono' is defined
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 3. The single, correct RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          // 4. Using the defined variables here is now correct
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar /> 
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}